######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 25 15:32:11 2009
######################################################################
CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += graph.h GraphException.h test.h
SOURCES += graph.cpp main.cpp test.cpp
QT += xml
