######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 25 16:04:01 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += jukeBox.h
FORMS += jukeBox.ui
SOURCES += jukeBox.cpp main.cpp
QT += xml
