package tuzova.finiteStateMachine.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class FiniteStateMachine_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("00d66c09-c182-4747-84e3-58794ed31fa9(tuzova.finiteStateMachine)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }

}
